name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c8f5d19d693dc0f39e03d43d18e427a2196697d46a69690d35973308e3ba86c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
