name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cd3b099a272dd044dacbb1fd0730b2785f33716acaea21f8c3f54252a41375a"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
