name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ee46a866141e29beb036cb869949e9716116d258c86be2751619cfeb2e26757"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
