name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c21b5b534dda5a770d91606046f2e390678229ee509f94514d97022ad475f81"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
