name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1cc0be87ff0971d14c5312b1096bf00e3310f08684eab22a9466899ec3ad127"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
