name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82553688dc0127cde6e60c5dbd30f9402a9005a34d9c4c9d50c9ce09cc14e1b6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
