name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c3ad3b84cd5f3ff5f792f3e368ec963ba6defbd50dc708f4b6265826414dc6b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
