name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9480c180a045c7fc88450c7f6a06fa555e65cd79898613abf631f3271c563cd"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
