name = "Teamountain Pack"
author = "yz"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c4cede7d3a9bc6fdeecd6e97c57d666d6e0d1390ca103b11f8f6f4cfcb36a3"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
