name = "FastBench for Fabric"
filename = "fastbench-1.18.1-3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/621/fastbench-1.18.1-3.jar"
hash-format = "murmur2"
hash = "1040113401"

[update]
[update.curseforge]
file-id = 3579621
project-id = 364531
