name = "TellMe"
filename = "tellme-fabric-1.18.0-0.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/162/tellme-fabric-1.18.0-0.9.0.jar"
hash-format = "murmur2"
hash = "2699087435"

[update]
[update.curseforge]
file-id = 3569162
project-id = 225781
